---
- name: deleting a user using variable
  hosts: all
  become: true

  vars:
    user: Roaster

  tasks:
    - name: deleting {{user}}
      user:
        name: "{{user}}"
        state: absent
...
