---
- name: error-handling file
  hosts: all
  become: true

  tasks:
    - name: install of httpd package
      yum:
        name: httpd
        state: installed
      notify: start apache
      when: ansible_os_family == "RedHat"

    - name: install of git package
      yum:
        name: gittt
        state: installed
      ignore_errors: yes

    - name: copying website file
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html/
        mode: 0666

  handlers:
    - name: start apache
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"
