---
- name: To install and start a service
  hosts: all
  become: true

  tasks:
    - name: to install a package
      yum:
        name: httpd
        state: installed
      notify: start apache

  handlers:
    - name: start apache
      service:
        name: httpd
        state: started
...
