---
- name: To install package and start a service
  hosts: all
  become: true
  tasks:
    - name: To install package
      yum:
        name: httpd
        state: installed

    - name: To start service
      service:
        name: httpd
        state: started
...
